---
apiVersion: v1
kind: Service
metadata:
  name: spc-service
  labels:
    app: spc
spec:
  type: LoadBalancer
  ports:
    - port: 9500
      targetPort: 8080
      protocol: TCP
  selector:
    app: spc